### ISSUE TITLE
Kantu causes error on click outside of root component in Angular2

### ISSUE THREAD

**Issue by mibzman** [A9T9/RPA#67] opened 2018-12-01 15:50 UTC
Hello,  I've recently discovered that in an application build with Angular2, any click outside the root component results in this error:
```
content_script.js:31496 Uncaught Error: getElementByLocator: fail to find element based on the locator, /html/html
    at getElementByLocator (content_script.js:31496)
    at getFirstWorkingLocator (content_script.js:25201)
    at Object.getLocator (content_script.js:25265)
    at HTMLDocument.onClick (content_script.js:34444)
```

**Comment by A9T9** [comment] 2018-12-03 12:03
hi, do you have a link to a website here we can test this?

**Comment by NicolasFenix** [comment] 2019-01-18 14:58
Hi, I've got the same issue. I didn't manage to reproduce this exact error, but I had it once (that's how I found this ticket). Now, I have this similar error : 

`content_script.js:39 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at m (content_script.js:39)
    at Object.v [as getLocator] (content_script.js:39)
    at HTMLDocument.U (content_script.js:48)`

Just go in "demo" on this website for example : 
https://svgnest.com/

**Comment by A9T9** [comment] 2019-01-20 11:17
Thanks for this useful test case. I confirmed that kantu has an issue with this website. We are looking into it. In the meantime you can use [xclick](https://a9t9.com/kantu/docs/xclick) with **image** locator as workaround.

This macro works:

![image1](https://user-images.githubusercontent.com/9657938/51438494-4d1a4d00-1cad-11e9-8e43-3e3201896930.png)

**Comment by A9T9** [comment] 2019-02-08 10:31
This issue should be fixed since the latest Kantu update. But please reopen if you still have a problem.

**Closed as completed by A9T9** 2019-02-08 10:31 UTC
